ci: compare image digests to check if rc and latest images are pushed correctly

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -254,12 +254,10 @@ jobs:
     strategy:
       matrix:
         include:
-          - registry: docker.io
-            image-name: source2adoc
+          - image-name: source2adoc
             context: .
             dockerfile: Dockerfile.app
-          - registry: docker.io
-            image-name: source2adoc-docs
+          - image-name: source2adoc-docs
             context: .
             dockerfile: Dockerfile.docs
     steps:
@@ -271,20 +269,19 @@ jobs:
           dockerfile: ${{ matrix.context }}/${{ matrix.dockerfile }}
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
-      - name: Login to Container Registry ${{ matrix.registry }}
+      - name: Login to Container Registry
         uses: docker/login-action@v3
         with:
-          registry: ${{ matrix.registry }}
           username: ${{ secrets.DOCKERHUB_USER }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Extract metadata (tags, labels) for Docker
         id: meta
         uses: docker/metadata-action@v5.5.1
         with:
-          images: ${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}
+          images: ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}
           labels: |
             org.opencontainers.image.revision=${{ github.sha }}
-      - name: Build the Docker image and push to ${{ matrix.registry }}
+      - name: Build the Docker image and push registry
         uses: docker/build-push-action@v6
         with:
           context: ${{ matrix.context }}
@@ -294,7 +291,7 @@ jobs:
             COMMIT_SHA=${{ github.sha }}
           platforms: linux/amd64
           push: true
-          tags: ${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}
+          tags: ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}
           labels: ${{ steps.meta.outputs.labels }}
           # cache-from: type=gha
           # cache-to: type=gha,mode=max
@@ -304,7 +301,7 @@ jobs:
         uses: docker/scout-action@v1.13.0
         with:
           command: cves
-          image: ${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}
+          image: ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}
           exit-code: false
           #write-comment: ${{ github.event_name == 'pull_request' }}
           write-comment: true
@@ -312,8 +309,8 @@ jobs:
         uses: docker/scout-action@v1.13.0
         with:
           command: compare
-          image: ${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}
-          to: ${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}
+          image: ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}
+          to: ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}
           exit-code: false
           #write-comment: ${{ github.event_name == 'pull_request' }}
           write-comment: true
@@ -328,22 +325,18 @@ jobs:
     env:
       CHEF_LICENSE: accept-no-persist
       CONTAINER_NAME: system_under_test
-    strategy: # see build-image (duplicated because github actions does not support anchors)
+    strategy:
       matrix:
-        include:
-          - registry: docker.io
-            image-name: source2adoc
-          - registry: docker.io
-            image-name: source2adoc-docs
+        image-name: ['source2adoc', 'source2adoc-docs']
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Install Inspec
         run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
         shell: bash
-      - name: Start system under test ${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}
+      - name: Start system under test ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}
         run: |
-          readonly IMAGE="${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}"
+          readonly IMAGE="${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}"
           docker pull "$IMAGE"
           docker run -d --name "${{ env.CONTAINER_NAME }}" --entrypoint tail "$IMAGE" -f /dev/null
         shell: bash
@@ -368,7 +361,7 @@ jobs:
               --no-distinct-exit
           )
         shell: bash
-      - name: Stop system under test ${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}
+      - name: Stop system under test ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}
         if: always()
         run: |
           docker stop --time 0 "${{ env.CONTAINER_NAME }}"
@@ -396,30 +389,25 @@ jobs:
     if: ${{ (github.actor != 'dependabot[bot]') && (github.ref == 'refs/heads/main') }}
     name: ${{ matrix.image-name }} as release candidate
     needs: ['inspec-image']
-    permissions: # see build-image (duplicated because github actions does not support anchors)
+    permissions:
       contents: read
       pull-requests: write
       security-events: write
-    strategy: # see build-image (duplicated because github actions does not support anchors)
+    strategy:
       matrix:
-        include:
-          - registry: docker.io
-            image-name: source2adoc
-          - registry: docker.io
-            image-name: source2adoc-docs
+        image-name: ['source2adoc', 'source2adoc-docs']
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-      - name: Login to Container Registry ${{ matrix.registry }}
+      - name: Login to Container Registry
         uses: docker/login-action@v3
         with:
-          registry: ${{ matrix.registry }}
           username: ${{ secrets.DOCKERHUB_USER }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Re-tag image as release candicate (:${{ env.IMAGE_TAG_RC }}) and deploy to ${{ matrix.registry }}
+      - name: Re-tag image as release candicate (:${{ env.IMAGE_TAG_RC }}) and deploy to registry
         run: |
-          SRC_IMAGE="${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}"
-          TARGET_IMAGE="${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}"
+          SRC_IMAGE="${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}"
+          TARGET_IMAGE="${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}"
           docker pull "$SRC_IMAGE"
           docker tag "$SRC_IMAGE" "$TARGET_IMAGE"
           docker push "$TARGET_IMAGE"
@@ -428,35 +416,53 @@ jobs:
         uses: docker/scout-action@v1.13.0
         with:
           command: compare
-          image: ${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}
-          to: ${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}
+          image: ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}
+          to: ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}
           exit-code: false
           #write-comment: ${{ github.event_name == 'pull_request' }}
           write-comment: true
 
-  validate-checksums:
+  validate-rc:
     runs-on: ubuntu-latest
     if: ${{ (github.actor != 'dependabot[bot]') && (github.ref == 'refs/heads/main') }}
     name: ${{ matrix.image-name }}
     needs: ['publish-rc']
     permissions:
       contents: read
-    strategy: # see build-image (duplicated because github actions does not support anchors)
+    strategy:
       matrix:
-        include:
-          - registry: docker.io
-            image-name: source2adoc
-          - registry: docker.io
-            image-name: source2adoc-docs
+        image-name: ['source2adoc', 'source2adoc-docs']
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+      - name: Pull ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}
+        run: docker pull ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}
+        shell: bash
+      - name: Pull ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}
+        run: docker pull ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}
+        shell: bash
+      - name: Compare digests
+        run: |
+          sha_digest=$(docker inspect --format='{{index .RepoDigests 0}}' "${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}")
+          rc_digest=$(docker inspect --format='{{index .RepoDigests 0}}' "${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}")
+
+          if [ "$sha_digest" != "$rc_digest" ]; then
+            echo "[ERROR] Images are not identical"
+            echo "[ERROR]      :sha | $sha_digest"
+            echo "[ERROR]       :rc | $rc_digest"
+            echo "[ERROR] exit code 1"
+            exit 1
+          else
+            echo "[INFO] Images are identical"
+            echo "[INFO] exit code 0"
+          fi
+        shell: bash
 
   # ----- Tag repository ------------------------
 
   release-code:
     runs-on: ubuntu-latest
-    needs: ['validate-checksums']
+    needs: ['validate-rc']
     if: ${{ (github.actor != 'dependabot[bot]') && (github.ref == 'refs/heads/main') }}
     permissions:
       contents: write
@@ -519,21 +525,17 @@ jobs:
   cleanup:
     runs-on: ubuntu-latest
     name: ${{ matrix.image-name }}
-    needs: ['validate-checksums']
+    needs: ['validate-rc']
     if: always()
     permissions:
       contents: read
-    strategy: # see build-image (duplicated because github actions does not support anchors)
+    strategy:
       matrix:
-        include:
-          - registry: docker.io
-            image-name: source2adoc
-          - registry: docker.io
-            image-name: source2adoc-docs
+        image-name: ['source2adoc', 'source2adoc-docs']
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-      - name: Remove :${{ github.sha }} images from ${{ matrix.registry }}
+      - name: Remove :${{ github.sha }} images from registry
         run: |
           TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'${{ secrets.DOCKERHUB_USER }}'", "password": "'${{ secrets.DOCKERHUB_TOKEN }}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
           curl -X DELETE -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}/tags/${{ github.sha }}/
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -24,11 +24,7 @@ jobs:
       contents: read
     strategy:
       matrix:
-        include:
-          - registry: docker.io
-            image-name: source2adoc
-          - registry: docker.io
-            image-name: source2adoc-docs
+        image-name: ['source2adoc', 'source2adoc-docs']
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -44,13 +40,13 @@ jobs:
 
           echo "New version tag = $TAG"
 
-          docker pull "${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}"
+          docker pull "${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}"
 
-          docker tag "${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}" "${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}"
-          docker tag "${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}" "${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:$TAG"
+          docker tag "${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}" "${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}"
+          docker tag "${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}" "${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:$TAG"
 
-          docker push "${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}"
-          docker push "${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:$TAG"
+          docker push "${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}"
+          docker push "${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:$TAG"
         shell: bash
       - name: Convert ${{ env.DOCS_FILE }} from Asciidoc to Markdown for DockerHub description
         run: |
@@ -69,6 +65,46 @@ jobs:
           short-description: ${{ github.event.repository.description }}
           readme-filepath: ./UPLOAD.md
 
+  validate-release:
+    runs-on: ubuntu-latest
+    if: ${{ (github.actor != 'dependabot[bot]') && (github.ref == 'refs/heads/main') }}
+    name: ${{ matrix.image-name }}
+    needs: ['publish-release']
+    permissions:
+      contents: read
+    strategy:
+      matrix:
+        image-name: ['source2adoc', 'source2adoc-docs']
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Pull ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}
+        run: docker pull ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ github.sha }}
+        shell: bash
+      - name: Pull ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}
+        run: docker pull ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}
+        shell: bash
+      - name: Compare digests
+        run: |
+          TAG="${GITHUB_REF#refs/tags/}"
+          TAG="${TAG#v}"
+
+          rc_digest=$(docker inspect --format='{{index .RepoDigests 0}}' "${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}")
+          latest_digest=$(docker inspect --format='{{index .RepoDigests 0}}' "${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}")
+          tag_digest=$(docker inspect --format='{{index .RepoDigests 0}}' "${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:$TAG")
+
+          if [ "$rc_digest" != "$latest_digest" ] || [ "$rc_digest" != "$tag_digest" ] || [ "$tag_digest" != "$latest_digest" ]; then
+            echo "[ERROR] Images are not identical"
+            echo "[ERROR]   :latest | $latest_digest"
+            echo "[ERROR]       :rc | $rc_digest"
+            echo "[ERROR] exit code 1"
+            exit 1
+          else
+            echo "[INFO] Images are identical"
+            echo "[INFO] exit code 0"
+          fi
+        shell: bash
+
   docker-scout-release:
     runs-on: ubuntu-latest
     needs: publish-release
@@ -80,25 +116,20 @@ jobs:
       CONTAINER_NAME: system_under_test
     strategy:
       matrix:
-        include:
-          - registry: docker.io
-            image-name: source2adoc
-          - registry: docker.io
-            image-name: source2adoc-docs
+        image-name: ['source2adoc', 'source2adoc-docs']
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-      - name: Login to Container Registry ${{ matrix.registry }}
+      - name: Login to Container Registry
         uses: docker/login-action@v3
         with:
-          registry: ${{ matrix.registry }}
           username: ${{ secrets.DOCKERHUB_USER }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Docker Scout CVEs for ${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}
         uses: docker/scout-action@v1.13.0
         with:
           command: cves
-          image: ${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}
+          image: ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}
           exit-code: false
           #write-comment: ${{ github.event_name == 'pull_request' }}
           write-comment: true
@@ -106,7 +137,7 @@ jobs:
         uses: docker/scout-action@v1.13.0
         with:
           command: compare
-          image: ${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}
-          to: ${{ matrix.registry }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}
+          image: ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_RC }}
+          to: ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}
           exit-code: false
           write-comment: true
